CREATE TABLE color (
    id_color INT PRIMARY KEY AUTO_INCREMENT,
    color VARCHAR(500) NOT NULL,
    hexadecimal VARCHAR(500) NOT NULL,
    user_crea VARCHAR(500) NOT NULL,
    fec_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE talla (
    id_talla INT PRIMARY KEY AUTO_INCREMENT,
    talla VARCHAR(500) NOT NULL,
    user_crea VARCHAR(500) NOT NULL,
    fec_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE categoria (
    id_categoria INT PRIMARY KEY AUTO_INCREMENT,
    categoria VARCHAR(500) NOT NULL,
    user_crea VARCHAR(500) NOT NULL,
    fec_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE material (
    id_material INT PRIMARY KEY AUTO_INCREMENT,
    material VARCHAR(500) NOT NULL,
    user_crea VARCHAR(500) NOT NULL,
    fec_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);